language: cpp
compiler: gcc
dist: xenial

branches:
    only:
        - master

jobs:
    include:
        - stage: Package
          name: "Packaging of mods"
          os: linux
          dist: xenial
          script:
            - ./build.sh
          after_success:
           - export GITHUB_TOKEN=$GH_TOKEN
           - wget -c https://github.com/FWGS/uploadtool/raw/master/upload.sh
           - bash upload.sh e2-patch.zip
